tmp
Signed-off-by: 170210 <j170210@icloud.com>

diff --git a/.github/workflows/check-generated.yml b/.github/workflows/check-generated.yml
--- a/.github/workflows/check-generated.yml
+++ b/.github/workflows/check-generated.yml
@@ -22,6 +22,10 @@ jobs:
       - name: Check generated error docs
         run: |
           make error-doc
+          if [ $? -ne 0 ]; then
+            echo "make run failure"
+            exit 1
+          fi
           if ! git diff --stat --exit-code ; then
             echo ">> ERROR:"
             echo ">>"
